### ISSUE TITLE
[Suggestion] AutoMine, AutoPlace, Stop momentum on flight disable

### ISSUE THREAD

**Issue by snnwer** [MeteorRejects/meteor-rejects#28]
- [x] MeteorDevelopment/meteor-client#1269
 - [x] MeteorDevelopment/meteor-client#1270

**Comment by StormyBytes** [comment]
AutoMine already exists in AutoClicker.

**Comment by C10udburst** [comment]
Added in 5a2bc0c64ae27cb2ac1f11aaec0bb2961890781a
